plotsc3p1 = plot(DATA{k,6}(1,1),DATA{k,6}(1,2),'x',...
    'MarkerEdgeColor',cmap(1,:)); hold on;
for i = 2:size(DATA{k,6},1)
    plot(DATA{k,6}(i,1),DATA{k,6}(i,2),'x',...
        'MarkerEdgeColor',cmap(i,:)); hold on;
end
if (isfield(problem,'plotrange'))
    if (isfield(problem.plotrange,'xmin') ...
            && isfield(problem.plotrange,'xmax') ...
            && isfield(problem.plotrange,'ymin') ...
            && isfield(problem.plotrange,'ymax'))
        axis([min(problem.plotrange.xmin, min(DATA{k,6}(:,1))) ...
            max(problem.plotrange.xmax, max(DATA{k,6}(:,1))) ...
            min(problem.plotrange.ymin, min(DATA{k,6}(:,2))) ...
            max(problem.plotrange.ymax, max(DATA{k,6}(:,2)))]);
    end
end
set(gca,'FontSize',16);
set(gca,'TickLabelInterpreter','latex');
xlabel('$f_1 = \max | \ddot{x}_1 (t) |$');
ylabel('$f_2 = \max | x_2 (t) - z (t) |$');
plotsc3gcaX = get(gca,'XLim');
plotsc3gcaY = get(gca,'YLim');
plotsc3txt1x = plotsc3gcaX(1) + 0.25*(plotsc3gcaX(2) - plotsc3gcaX(1));
plotsc3txt1y = plotsc3gcaY(1) + 0.1*(plotsc3gcaY(2) - plotsc3gcaY(1));
text(plotsc3txt1x,plotsc3txt1y,'$\Leftarrow$ Comfort',...
    'FontSize',18);
plotsc3txt2x = plotsc3gcaX(1) + 0.1*(plotsc3gcaX(2) - plotsc3gcaX(1));
plotsc3txt2y = plotsc3gcaY(1) + 0.25*(plotsc3gcaY(2) - plotsc3gcaY(1));
text(plotsc3txt2x,plotsc3txt2y,'$\Leftarrow$ Handling',...
    'FontSize',18,'Rotation',90);

legend([plotsc3p1],{'predicted Pareto set'},...
    'Location','northeast','Interpreter','latex','FontSize',16);

for i = 1:size(DATA{k,10}(:,1),1)
    plot([DATA{k,10}(i,1),DATA{k,11}(i,1)],...
        [DATA{k,10}(i,2),DATA{k,11}(i,2)],'k:','LineWidth',1.5); hold on;
end
plotsc3p9 = plot(DATA{k,10}(:,1),DATA{k,10}(:,2),'+',...
    'MarkerEdgeColor',[0 0 0],'MarkerSize',10,'LineWidth',2); hold on;
plotsc3p10 = plot(DATA{k,11}(:,1),DATA{k,11}(:,2),'s',...
    'MarkerEdgeColor',[0 0 0],'MarkerSize',10,'LineWidth',2); hold on;
if (isfield(problem,'plotrange'))
    if (isfield(problem.plotrange,'xmin') ...
            && isfield(problem.plotrange,'xmax') ...
            && isfield(problem.plotrange,'ymin') ...
            && isfield(problem.plotrange,'ymax'))
        axis([min(problem.plotrange.xmin,...
                min(min(DATA{k,6}(:,1)),...
                min(min(DATA{k,10}(:,1)),min(DATA{k,11}(:,1))))) ...
            max(problem.plotrange.xmax,...
                max(max(DATA{k,6}(:,1)),...
                max(max(DATA{k,10}(:,1)),max(DATA{k,11}(:,1))))) ...
            min(problem.plotrange.ymin,...
                min(min(DATA{k,6}(:,2)),...
                min(min(DATA{k,10}(:,2)),min(DATA{k,11}(:,2))))) ...
            max(problem.plotrange.ymax,...
                max(max(DATA{k,6}(:,2)),...
                max(max(DATA{k,10}(:,2)),max(DATA{k,11}(:,2)))))]);
    end
end
legend([plotsc3p1,plotsc3p9,plotsc3p10],{'predicted Pareto set','validation point',...
    'high fidelity fn result'},...
    'Location','northeast','Interpreter','latex','FontSize',16);